const REGISTRY_FILE_CREATE_STATUS = 'confirmed'
const REGISTRY_FILE_READY_TO_PUBLISH_STATUS = 'parsed'
const REGISTRY_FILE_APPROVED_STATUS = 'publishing'

const HOUSING_CATEGORY_ID = ''
const OVERHAUL_CATEGORY_ID = ''

const DOMA_FORMAT = 'DOMA_XLSX'
const DOMA_EXTENDED_FORMAT = 'DOMA_XLSX_DETAILED'

module.exports = {
    REGISTRY_FILE_CREATE_STATUS,
    REGISTRY_FILE_READY_TO_PUBLISH_STATUS,
    REGISTRY_FILE_APPROVED_STATUS,
    HOUSING_CATEGORY_ID,
    OVERHAUL_CATEGORY_ID,
    DOMA_FORMAT,
    DOMA_EXTENDED_FORMAT,
}