const REGISTRY_FILE_CREATE_STATUS = 'confirmed'
const REGISTRY_FILE_READY_TO_PUBLISH_STATUS = 'parsed'
const REGISTRY_FILE_APPROVED_STATUS = 'publishing'
const REGISTRY_FILE_DONE_STATUS = 'completed'

const HOUSING_CATEGORY_ID = '928c97ef-5289-4daa-b80e-4b9fed50c629'
const OVERHAUL_CATEGORY_ID = 'c0b9db6a-c351-4bf4-aa35-8e5a500d0195'

const DOMA_FORMAT = 'DOMA_XLSX'
const DOMA_EXTENDED_FORMAT = 'DOMA_XLSX_DETAILED'

module.exports = {
    REGISTRY_FILE_CREATE_STATUS,
    REGISTRY_FILE_READY_TO_PUBLISH_STATUS,
    REGISTRY_FILE_APPROVED_STATUS,
    REGISTRY_FILE_DONE_STATUS,
    HOUSING_CATEGORY_ID,
    OVERHAUL_CATEGORY_ID,
    DOMA_FORMAT,
    DOMA_EXTENDED_FORMAT,
}